/*! File generated by TLObjects' generator. All changes will be ERASED !*/
const { TLObject } = require('../tlobject');
const struct = require('python-struct');
const { readBigIntFromBuffer, 
        readBufferFromBigInt, generateRandomBytes } = require('../../Helpers')


class SentCode extends TLObject {
    static CONSTRUCTOR_ID = 0x5e002502;
    static SUBCLASS_OF_ID = 0x6ce87081;

    /**
    Constructor for auth.SentCode: Instance of SentCode
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x5e002502;
        this.SUBCLASS_OF_ID = 0x6ce87081;

        this.type = args.type;
        this.phoneCodeHash = args.phoneCodeHash;
        this.nextType = args.nextType || null;
        this.timeout = args.timeout || null;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("0225005e","hex"),
            struct.pack('<I', (this.nextType === undefined || this.nextType === false || this.nextType === null) ? 0 : 2 | (this.timeout === undefined || this.timeout === false || this.timeout === null) ? 0 : 4),
            this.type.getBytes(),
            TLObject.serializeBytes(this.phoneCodeHash),
            (this.nextType === undefined || this.nextType === false || this.nextType ===null) ? Buffer.alloc(0) : [this.nextType.getBytes()],
            (this.timeout === undefined || this.timeout === false || this.timeout ===null) ? Buffer.alloc(0) : [struct.pack('<i', this.timeout)],
            ])
        }
    static fromReader(reader) {
        let _flags;
        let _type;
        let _phone_code_hash;
        let _next_type;
        let _timeout;
        let _x;
        let len;
        let flags = reader.readInt();

        _type = reader.tgReadObject();
        _phone_code_hash = reader.tgReadString();
        if (flags & 2) {
            _next_type = reader.tgReadObject();
        }
        else {
            _next_type = null
        }
        if (flags & 4) {
            _timeout = reader.readInt();
        }
        else {
            _timeout = null
        }
        return new this({type:_type,
	phoneCodeHash:_phone_code_hash,
	nextType:_next_type,
	timeout:_timeout})
    }
}


class Authorization extends TLObject {
    static CONSTRUCTOR_ID = 0xcd050916;
    static SUBCLASS_OF_ID = 0xb9e04e39;

    /**
    Constructor for auth.Authorization: Instance of either Authorization, AuthorizationSignUpRequired
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0xcd050916;
        this.SUBCLASS_OF_ID = 0xb9e04e39;

        this.tmpSessions = args.tmpSessions || null;
        this.user = args.user;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("160905cd","hex"),
            struct.pack('<I', (this.tmpSessions === undefined || this.tmpSessions === false || this.tmpSessions === null) ? 0 : 1),
            (this.tmpSessions === undefined || this.tmpSessions === false || this.tmpSessions ===null) ? Buffer.alloc(0) : [struct.pack('<i', this.tmpSessions)],
            this.user.getBytes(),
            ])
        }
    static fromReader(reader) {
        let _flags;
        let _tmp_sessions;
        let _user;
        let _x;
        let len;
        let flags = reader.readInt();

        if (flags & 1) {
            _tmp_sessions = reader.readInt();
        }
        else {
            _tmp_sessions = null
        }
        _user = reader.tgReadObject();
        return new this({tmpSessions:_tmp_sessions,
	user:_user})
    }
}


class AuthorizationSignUpRequired extends TLObject {
    static CONSTRUCTOR_ID = 0x44747e9a;
    static SUBCLASS_OF_ID = 0xb9e04e39;

    /**
    Constructor for auth.Authorization: Instance of either Authorization, AuthorizationSignUpRequired
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x44747e9a;
        this.SUBCLASS_OF_ID = 0xb9e04e39;

        this.termsOfService = args.termsOfService || null;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("9a7e7444","hex"),
            struct.pack('<I', (this.termsOfService === undefined || this.termsOfService === false || this.termsOfService === null) ? 0 : 1),
            (this.termsOfService === undefined || this.termsOfService === false || this.termsOfService ===null) ? Buffer.alloc(0) : [this.termsOfService.getBytes()],
            ])
        }
    static fromReader(reader) {
        let _flags;
        let _terms_of_service;
        let _x;
        let len;
        let flags = reader.readInt();

        if (flags & 1) {
            _terms_of_service = reader.tgReadObject();
        }
        else {
            _terms_of_service = null
        }
        return new this({termsOfService:_terms_of_service})
    }
}


class ExportedAuthorization extends TLObject {
    static CONSTRUCTOR_ID = 0xdf969c2d;
    static SUBCLASS_OF_ID = 0x5fd1ec51;

    /**
    Constructor for auth.ExportedAuthorization: Instance of ExportedAuthorization
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0xdf969c2d;
        this.SUBCLASS_OF_ID = 0x5fd1ec51;

        this.id = args.id;
        this.bytes = args.bytes;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("2d9c96df","hex"),
            struct.pack('<i', this.id),
            TLObject.serializeBytes(this.bytes),
            ])
        }
    static fromReader(reader) {
        let _id;
        let _bytes;
        let _x;
        let len;
        _id = reader.readInt();
        _bytes = reader.tgReadBytes();
        return new this({id:_id,
	bytes:_bytes})
    }
}


class PasswordRecovery extends TLObject {
    static CONSTRUCTOR_ID = 0x137948a5;
    static SUBCLASS_OF_ID = 0xfa72d43a;

    /**
    Constructor for auth.PasswordRecovery: Instance of PasswordRecovery
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x137948a5;
        this.SUBCLASS_OF_ID = 0xfa72d43a;

        this.emailPattern = args.emailPattern;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("a5487913","hex"),
            TLObject.serializeBytes(this.emailPattern),
            ])
        }
    static fromReader(reader) {
        let _email_pattern;
        let _x;
        let len;
        _email_pattern = reader.tgReadString();
        return new this({emailPattern:_email_pattern})
    }
}


class CodeTypeSms extends TLObject {
    static CONSTRUCTOR_ID = 0x72a3158c;
    static SUBCLASS_OF_ID = 0xb3f3e401;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0x72a3158c;
        this.SUBCLASS_OF_ID = 0xb3f3e401;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("8c15a372","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class CodeTypeCall extends TLObject {
    static CONSTRUCTOR_ID = 0x741cd3e3;
    static SUBCLASS_OF_ID = 0xb3f3e401;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0x741cd3e3;
        this.SUBCLASS_OF_ID = 0xb3f3e401;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("e3d31c74","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class CodeTypeFlashCall extends TLObject {
    static CONSTRUCTOR_ID = 0x226ccefb;
    static SUBCLASS_OF_ID = 0xb3f3e401;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0x226ccefb;
        this.SUBCLASS_OF_ID = 0xb3f3e401;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("fbce6c22","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class SentCodeTypeApp extends TLObject {
    static CONSTRUCTOR_ID = 0x3dbb5986;
    static SUBCLASS_OF_ID = 0xff5b158e;

    /**
    Constructor for auth.SentCodeType: Instance of either SentCodeTypeApp, SentCodeTypeSms, SentCodeTypeCall, SentCodeTypeFlashCall
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x3dbb5986;
        this.SUBCLASS_OF_ID = 0xff5b158e;

        this.length = args.length;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("8659bb3d","hex"),
            struct.pack('<i', this.length),
            ])
        }
    static fromReader(reader) {
        let _length;
        let _x;
        let len;
        _length = reader.readInt();
        return new this({length:_length})
    }
}


class SentCodeTypeSms extends TLObject {
    static CONSTRUCTOR_ID = 0xc000bba2;
    static SUBCLASS_OF_ID = 0xff5b158e;

    /**
    Constructor for auth.SentCodeType: Instance of either SentCodeTypeApp, SentCodeTypeSms, SentCodeTypeCall, SentCodeTypeFlashCall
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0xc000bba2;
        this.SUBCLASS_OF_ID = 0xff5b158e;

        this.length = args.length;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("a2bb00c0","hex"),
            struct.pack('<i', this.length),
            ])
        }
    static fromReader(reader) {
        let _length;
        let _x;
        let len;
        _length = reader.readInt();
        return new this({length:_length})
    }
}


class SentCodeTypeCall extends TLObject {
    static CONSTRUCTOR_ID = 0x5353e5a7;
    static SUBCLASS_OF_ID = 0xff5b158e;

    /**
    Constructor for auth.SentCodeType: Instance of either SentCodeTypeApp, SentCodeTypeSms, SentCodeTypeCall, SentCodeTypeFlashCall
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x5353e5a7;
        this.SUBCLASS_OF_ID = 0xff5b158e;

        this.length = args.length;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("a7e55353","hex"),
            struct.pack('<i', this.length),
            ])
        }
    static fromReader(reader) {
        let _length;
        let _x;
        let len;
        _length = reader.readInt();
        return new this({length:_length})
    }
}


class SentCodeTypeFlashCall extends TLObject {
    static CONSTRUCTOR_ID = 0xab03c6d9;
    static SUBCLASS_OF_ID = 0xff5b158e;

    /**
    Constructor for auth.SentCodeType: Instance of either SentCodeTypeApp, SentCodeTypeSms, SentCodeTypeCall, SentCodeTypeFlashCall
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0xab03c6d9;
        this.SUBCLASS_OF_ID = 0xff5b158e;

        this.pattern = args.pattern;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("d9c603ab","hex"),
            TLObject.serializeBytes(this.pattern),
            ])
        }
    static fromReader(reader) {
        let _pattern;
        let _x;
        let len;
        _pattern = reader.tgReadString();
        return new this({pattern:_pattern})
    }
}

module.exports = {
    SentCode,
    Authorization,
    AuthorizationSignUpRequired,
    ExportedAuthorization,
    PasswordRecovery,
    CodeTypeSms,
    CodeTypeCall,
    CodeTypeFlashCall,
    SentCodeTypeApp,
    SentCodeTypeSms,
    SentCodeTypeCall,
    SentCodeTypeFlashCall,
};
