/*! File generated by TLObjects' generator. All changes will be ERASED !*/
const { TLObject } = require('../tlobject');
const struct = require('python-struct');
const { readBigIntFromBuffer, 
        readBufferFromBigInt, generateRandomBytes } = require('../../Helpers')


class PaymentForm extends TLObject {
    static CONSTRUCTOR_ID = 0x3f56aea3;
    static SUBCLASS_OF_ID = 0xa0483f19;

    /**
    Constructor for payments.PaymentForm: Instance of PaymentForm
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x3f56aea3;
        this.SUBCLASS_OF_ID = 0xa0483f19;

        this.canSaveCredentials = args.canSaveCredentials || null;
        this.passwordMissing = args.passwordMissing || null;
        this.botId = args.botId;
        this.invoice = args.invoice;
        this.providerId = args.providerId;
        this.url = args.url;
        this.nativeProvider = args.nativeProvider || null;
        this.nativeParams = args.nativeParams || null;
        this.savedInfo = args.savedInfo || null;
        this.savedCredentials = args.savedCredentials || null;
        this.users = args.users;
    }
    getBytes() {
        if (!((this.native_provider || this.native_provider!==null && this.native_params || this.native_params!==null) && (this.native_provider===null || this.native_provider===false && this.native_params===null || this.native_params===false)))
	 throw new Error('native_provider, native_params paramaters must all be false-y or all true')
        return Buffer.concat([
            Buffer.from("a3ae563f","hex"),
            struct.pack('<I', (this.canSaveCredentials === undefined || this.canSaveCredentials === false || this.canSaveCredentials === null) ? 0 : 4 | (this.passwordMissing === undefined || this.passwordMissing === false || this.passwordMissing === null) ? 0 : 8 | (this.nativeProvider === undefined || this.nativeProvider === false || this.nativeProvider === null) ? 0 : 16 | (this.nativeParams === undefined || this.nativeParams === false || this.nativeParams === null) ? 0 : 16 | (this.savedInfo === undefined || this.savedInfo === false || this.savedInfo === null) ? 0 : 1 | (this.savedCredentials === undefined || this.savedCredentials === false || this.savedCredentials === null) ? 0 : 2),
            struct.pack('<i', this.botId),
            this.invoice.getBytes(),
            struct.pack('<i', this.providerId),
            TLObject.serializeBytes(this.url),
            (this.nativeProvider === undefined || this.nativeProvider === false || this.nativeProvider ===null) ? Buffer.alloc(0) : [TLObject.serializeBytes(this.nativeProvider)],
            (this.nativeParams === undefined || this.nativeParams === false || this.nativeParams ===null) ? Buffer.alloc(0) : [this.nativeParams.getBytes()],
            (this.savedInfo === undefined || this.savedInfo === false || this.savedInfo ===null) ? Buffer.alloc(0) : [this.savedInfo.getBytes()],
            (this.savedCredentials === undefined || this.savedCredentials === false || this.savedCredentials ===null) ? Buffer.alloc(0) : [this.savedCredentials.getBytes()],
            Buffer.from('15c4b51c', 'hex'),struct.pack('<i', this.users.length),Buffer.concat(this.users.map(x => x.getBytes())),
            ])
        }
    static fromReader(reader) {
        let _flags;
        let _can_save_credentials;
        let _password_missing;
        let _bot_id;
        let _invoice;
        let _provider_id;
        let _url;
        let _native_provider;
        let _native_params;
        let _saved_info;
        let _saved_credentials;
        let _users;
        let _x;
        let len;
        let flags = reader.readInt();

        _can_save_credentials = Boolean(flags & 4);
        _password_missing = Boolean(flags & 8);
        _bot_id = reader.readInt();
        _invoice = reader.tgReadObject();
        _provider_id = reader.readInt();
        _url = reader.tgReadString();
        if (flags & 16) {
            _native_provider = reader.tgReadString();
        }
        else {
            _native_provider = null
        }
        if (flags & 16) {
            _native_params = reader.tgReadObject();
        }
        else {
            _native_params = null
        }
        if (flags & 1) {
            _saved_info = reader.tgReadObject();
        }
        else {
            _saved_info = null
        }
        if (flags & 2) {
            _saved_credentials = reader.tgReadObject();
        }
        else {
            _saved_credentials = null
        }
        reader.readInt();
        _users = [];
        len = reader.readInt();
        for (let i=0;i<len;i++){
            _x = reader.tgReadObject();
            _users.push(_x);
            }
            return new this({canSaveCredentials:_can_save_credentials,
	passwordMissing:_password_missing,
	botId:_bot_id,
	invoice:_invoice,
	providerId:_provider_id,
	url:_url,
	nativeProvider:_native_provider,
	nativeParams:_native_params,
	savedInfo:_saved_info,
	savedCredentials:_saved_credentials,
	users:_users})
        }
    }


class ValidatedRequestedInfo extends TLObject {
    static CONSTRUCTOR_ID = 0xd1451883;
    static SUBCLASS_OF_ID = 0x8f8044b7;

    /**
    Constructor for payments.ValidatedRequestedInfo: Instance of ValidatedRequestedInfo
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0xd1451883;
        this.SUBCLASS_OF_ID = 0x8f8044b7;

        this.id = args.id || null;
        this.shippingOptions = args.shippingOptions || null;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("831845d1","hex"),
            struct.pack('<I', (this.id === undefined || this.id === false || this.id === null) ? 0 : 1 | (this.shippingOptions === undefined || this.shippingOptions === false || this.shippingOptions === null) ? 0 : 2),
            (this.id === undefined || this.id === false || this.id ===null) ? Buffer.alloc(0) : [TLObject.serializeBytes(this.id)],
            (this.shippingOptions === undefined || this.shippingOptions === false || this.shippingOptions ===null) ? Buffer.alloc(0) :Buffer.concat([Buffer.from('15c4b51c', 'hex'),struct.pack('<i', this.shippingOptions.length),Buffer.concat(this.shippingOptions.map(x => x.getBytes()))]),
            ])
        }
    static fromReader(reader) {
        let _flags;
        let _id;
        let _shipping_options;
        let _x;
        let len;
        let flags = reader.readInt();

        if (flags & 1) {
            _id = reader.tgReadString();
        }
        else {
            _id = null
        }
        if (flags & 2) {
            reader.readInt();
            _shipping_options = [];
            len = reader.readInt();
            for (let i=0;i<len;i++){
                _x = reader.tgReadObject();
                _shipping_options.push(_x);
                }
            }
            else {
                _shipping_options = null
            }
            return new this({id:_id,
	shippingOptions:_shipping_options})
        }
    }


class PaymentResult extends TLObject {
    static CONSTRUCTOR_ID = 0x4e5f810d;
    static SUBCLASS_OF_ID = 0x8ae16a9d;

    /**
    Constructor for payments.PaymentResult: Instance of either PaymentResult, PaymentVerificationNeeded
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x4e5f810d;
        this.SUBCLASS_OF_ID = 0x8ae16a9d;

        this.updates = args.updates;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("0d815f4e","hex"),
            this.updates.getBytes(),
            ])
        }
    static fromReader(reader) {
        let _updates;
        let _x;
        let len;
        _updates = reader.tgReadObject();
        return new this({updates:_updates})
    }
}


class PaymentVerificationNeeded extends TLObject {
    static CONSTRUCTOR_ID = 0xd8411139;
    static SUBCLASS_OF_ID = 0x8ae16a9d;

    /**
    Constructor for payments.PaymentResult: Instance of either PaymentResult, PaymentVerificationNeeded
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0xd8411139;
        this.SUBCLASS_OF_ID = 0x8ae16a9d;

        this.url = args.url;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("391141d8","hex"),
            TLObject.serializeBytes(this.url),
            ])
        }
    static fromReader(reader) {
        let _url;
        let _x;
        let len;
        _url = reader.tgReadString();
        return new this({url:_url})
    }
}


class PaymentReceipt extends TLObject {
    static CONSTRUCTOR_ID = 0x500911e1;
    static SUBCLASS_OF_ID = 0x590093c9;

    /**
    Constructor for payments.PaymentReceipt: Instance of PaymentReceipt
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x500911e1;
        this.SUBCLASS_OF_ID = 0x590093c9;

        this.date = args.date;
        this.botId = args.botId;
        this.invoice = args.invoice;
        this.providerId = args.providerId;
        this.info = args.info || null;
        this.shipping = args.shipping || null;
        this.currency = args.currency;
        this.totalAmount = args.totalAmount;
        this.credentialsTitle = args.credentialsTitle;
        this.users = args.users;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("e1110950","hex"),
            struct.pack('<I', (this.info === undefined || this.info === false || this.info === null) ? 0 : 1 | (this.shipping === undefined || this.shipping === false || this.shipping === null) ? 0 : 2),
            struct.pack('<i', this.date),
            struct.pack('<i', this.botId),
            this.invoice.getBytes(),
            struct.pack('<i', this.providerId),
            (this.info === undefined || this.info === false || this.info ===null) ? Buffer.alloc(0) : [this.info.getBytes()],
            (this.shipping === undefined || this.shipping === false || this.shipping ===null) ? Buffer.alloc(0) : [this.shipping.getBytes()],
            TLObject.serializeBytes(this.currency),
            readBufferFromBigInt(this.totalAmount,8,true,true),
            TLObject.serializeBytes(this.credentialsTitle),
            Buffer.from('15c4b51c', 'hex'),struct.pack('<i', this.users.length),Buffer.concat(this.users.map(x => x.getBytes())),
            ])
        }
    static fromReader(reader) {
        let _flags;
        let _date;
        let _bot_id;
        let _invoice;
        let _provider_id;
        let _info;
        let _shipping;
        let _currency;
        let _total_amount;
        let _credentials_title;
        let _users;
        let _x;
        let len;
        let flags = reader.readInt();

        _date = reader.readInt();
        _bot_id = reader.readInt();
        _invoice = reader.tgReadObject();
        _provider_id = reader.readInt();
        if (flags & 1) {
            _info = reader.tgReadObject();
        }
        else {
            _info = null
        }
        if (flags & 2) {
            _shipping = reader.tgReadObject();
        }
        else {
            _shipping = null
        }
        _currency = reader.tgReadString();
        _total_amount = reader.readLong();
        _credentials_title = reader.tgReadString();
        reader.readInt();
        _users = [];
        len = reader.readInt();
        for (let i=0;i<len;i++){
            _x = reader.tgReadObject();
            _users.push(_x);
            }
            return new this({date:_date,
	botId:_bot_id,
	invoice:_invoice,
	providerId:_provider_id,
	info:_info,
	shipping:_shipping,
	currency:_currency,
	totalAmount:_total_amount,
	credentialsTitle:_credentials_title,
	users:_users})
        }
    }


class SavedInfo extends TLObject {
    static CONSTRUCTOR_ID = 0xfb8fe43c;
    static SUBCLASS_OF_ID = 0xad3cf146;

    /**
    Constructor for payments.SavedInfo: Instance of SavedInfo
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0xfb8fe43c;
        this.SUBCLASS_OF_ID = 0xad3cf146;

        this.hasSavedCredentials = args.hasSavedCredentials || null;
        this.savedInfo = args.savedInfo || null;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("3ce48ffb","hex"),
            struct.pack('<I', (this.hasSavedCredentials === undefined || this.hasSavedCredentials === false || this.hasSavedCredentials === null) ? 0 : 2 | (this.savedInfo === undefined || this.savedInfo === false || this.savedInfo === null) ? 0 : 1),
            (this.savedInfo === undefined || this.savedInfo === false || this.savedInfo ===null) ? Buffer.alloc(0) : [this.savedInfo.getBytes()],
            ])
        }
    static fromReader(reader) {
        let _flags;
        let _has_saved_credentials;
        let _saved_info;
        let _x;
        let len;
        let flags = reader.readInt();

        _has_saved_credentials = Boolean(flags & 2);
        if (flags & 1) {
            _saved_info = reader.tgReadObject();
        }
        else {
            _saved_info = null
        }
        return new this({hasSavedCredentials:_has_saved_credentials,
	savedInfo:_saved_info})
    }
}

module.exports = {
    PaymentForm,
    ValidatedRequestedInfo,
    PaymentResult,
    PaymentVerificationNeeded,
    PaymentReceipt,
    SavedInfo,
};
