/*! File generated by TLObjects' generator. All changes will be ERASED !*/
const { TLObject } = require('../tlobject');
const { TLRequest } = require('../tlobject');
const struct = require('python-struct');
const { readBigIntFromBuffer, 
        readBufferFromBigInt, generateRandomBytes } = require('../../Helpers')


class GetConfigRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0xc4f9186b;
    static SUBCLASS_OF_ID = 0xd3262a4a;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0xc4f9186b;
        this.SUBCLASS_OF_ID = 0xd3262a4a;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("6b18f9c4","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class GetNearestDcRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x1fb33026;
    static SUBCLASS_OF_ID = 0x3877045f;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0x1fb33026;
        this.SUBCLASS_OF_ID = 0x3877045f;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("2630b31f","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class GetAppUpdateRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x522d5a7d;
    static SUBCLASS_OF_ID = 0x5897069e;

    /**
    :returns help.AppUpdate: Instance of either AppUpdate, NoAppUpdate
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x522d5a7d;
        this.SUBCLASS_OF_ID = 0x5897069e;

        this.source = args.source;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("7d5a2d52","hex"),
            TLObject.serializeBytes(this.source),
            ])
        }
    static fromReader(reader) {
        let _source;
        let _x;
        let len;
        _source = reader.tgReadString();
        return new this({source:_source})
    }
}


class GetInviteTextRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x4d392343;
    static SUBCLASS_OF_ID = 0xcf70aa35;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0x4d392343;
        this.SUBCLASS_OF_ID = 0xcf70aa35;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("4323394d","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class GetSupportRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x9cdf08cd;
    static SUBCLASS_OF_ID = 0x7159bceb;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0x9cdf08cd;
        this.SUBCLASS_OF_ID = 0x7159bceb;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("cd08df9c","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class GetAppChangelogRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x9010ef6f;
    static SUBCLASS_OF_ID = 0x8af52aac;

    /**
    :returns Updates: Instance of either UpdatesTooLong, UpdateShortMessage, UpdateShortChatMessage, UpdateShort, UpdatesCombined, Updates, UpdateShortSentMessage
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x9010ef6f;
        this.SUBCLASS_OF_ID = 0x8af52aac;

        this.prevAppVersion = args.prevAppVersion;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("6fef1090","hex"),
            TLObject.serializeBytes(this.prevAppVersion),
            ])
        }
    static fromReader(reader) {
        let _prev_app_version;
        let _x;
        let len;
        _prev_app_version = reader.tgReadString();
        return new this({prevAppVersion:_prev_app_version})
    }
}


class SetBotUpdatesStatusRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0xec22cfcd;
    static SUBCLASS_OF_ID = 0xf5b399ac;

    /**
    :returns Bool: This type has no constructors.
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0xec22cfcd;
        this.SUBCLASS_OF_ID = 0xf5b399ac;

        this.pendingUpdatesCount = args.pendingUpdatesCount;
        this.message = args.message;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("cdcf22ec","hex"),
            struct.pack('<i', this.pendingUpdatesCount),
            TLObject.serializeBytes(this.message),
            ])
        }
    static fromReader(reader) {
        let _pending_updates_count;
        let _message;
        let _x;
        let len;
        _pending_updates_count = reader.readInt();
        _message = reader.tgReadString();
        return new this({pendingUpdatesCount:_pending_updates_count,
	message:_message})
    }
}


class GetCdnConfigRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x52029342;
    static SUBCLASS_OF_ID = 0xecda397c;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0x52029342;
        this.SUBCLASS_OF_ID = 0xecda397c;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("42930252","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class GetRecentMeUrlsRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x3dc0f114;
    static SUBCLASS_OF_ID = 0xf269c477;

    /**
    :returns help.RecentMeUrls: Instance of RecentMeUrls
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x3dc0f114;
        this.SUBCLASS_OF_ID = 0xf269c477;

        this.referer = args.referer;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("14f1c03d","hex"),
            TLObject.serializeBytes(this.referer),
            ])
        }
    static fromReader(reader) {
        let _referer;
        let _x;
        let len;
        _referer = reader.tgReadString();
        return new this({referer:_referer})
    }
}


class GetProxyDataRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x3d7758e1;
    static SUBCLASS_OF_ID = 0x21e2a448;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0x3d7758e1;
        this.SUBCLASS_OF_ID = 0x21e2a448;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("e158773d","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class GetTermsOfServiceUpdateRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x2ca51fd1;
    static SUBCLASS_OF_ID = 0x293c2977;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0x2ca51fd1;
        this.SUBCLASS_OF_ID = 0x293c2977;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("d11fa52c","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class AcceptTermsOfServiceRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0xee72f79a;
    static SUBCLASS_OF_ID = 0xf5b399ac;

    /**
    :returns Bool: This type has no constructors.
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0xee72f79a;
        this.SUBCLASS_OF_ID = 0xf5b399ac;

        this.id = args.id;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("9af772ee","hex"),
            this.id.getBytes(),
            ])
        }
    static fromReader(reader) {
        let _id;
        let _x;
        let len;
        _id = reader.tgReadObject();
        return new this({id:_id})
    }
}


class GetDeepLinkInfoRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x3fedc75f;
    static SUBCLASS_OF_ID = 0x984aac38;

    /**
    :returns help.DeepLinkInfo: Instance of either DeepLinkInfoEmpty, DeepLinkInfo
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x3fedc75f;
        this.SUBCLASS_OF_ID = 0x984aac38;

        this.path = args.path;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("5fc7ed3f","hex"),
            TLObject.serializeBytes(this.path),
            ])
        }
    static fromReader(reader) {
        let _path;
        let _x;
        let len;
        _path = reader.tgReadString();
        return new this({path:_path})
    }
}


class GetAppConfigRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x98914110;
    static SUBCLASS_OF_ID = 0xeb9987b3;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0x98914110;
        this.SUBCLASS_OF_ID = 0xeb9987b3;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("10419198","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class SaveAppLogRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x6f02f748;
    static SUBCLASS_OF_ID = 0xf5b399ac;

    /**
    :returns Bool: This type has no constructors.
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x6f02f748;
        this.SUBCLASS_OF_ID = 0xf5b399ac;

        this.events = args.events;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("48f7026f","hex"),
            Buffer.from('15c4b51c', 'hex'),struct.pack('<i', this.events.length),Buffer.concat(this.events.map(x => x.getBytes())),
            ])
        }
    static fromReader(reader) {
        let _events;
        let _x;
        let len;
        reader.readInt();
        _events = [];
        len = reader.readInt();
        for (let i=0;i<len;i++){
            _x = reader.tgReadObject();
            _events.push(_x);
            }
            return new this({events:_events})
        }
    }


class GetPassportConfigRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0xc661ad08;
    static SUBCLASS_OF_ID = 0xc666c0ad;

    /**
    :returns help.PassportConfig: Instance of either PassportConfigNotModified, PassportConfig
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0xc661ad08;
        this.SUBCLASS_OF_ID = 0xc666c0ad;

        this.hash = args.hash;
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("08ad61c6","hex"),
            struct.pack('<i', this.hash),
            ])
        }
    static fromReader(reader) {
        let _hash;
        let _x;
        let len;
        _hash = reader.readInt();
        return new this({hash:_hash})
    }
}


class GetSupportNameRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0xd360e72c;
    static SUBCLASS_OF_ID = 0x7f50b7c2;

    constructor() {
        super();
        this.CONSTRUCTOR_ID = 0xd360e72c;
        this.SUBCLASS_OF_ID = 0x7f50b7c2;

    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("2ce760d3","hex"),
            ])
        }
    static fromReader(reader) {
        let _x;
        let len;
        return new this({})
    }
}


class GetUserInfoRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x038a08d3;
    static SUBCLASS_OF_ID = 0x5c53d7d8;

    /**
    :returns help.UserInfo: Instance of either UserInfoEmpty, UserInfo
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x038a08d3;
        this.SUBCLASS_OF_ID = 0x5c53d7d8;

        this.userId = args.userId;
    }
    async resolve(client, utils) {
        this.user_id = utils.getInputUser(await client.getInputEntity(this.userId))
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("d3088a03","hex"),
            this.userId.getBytes(),
            ])
        }
    static fromReader(reader) {
        let _user_id;
        let _x;
        let len;
        _user_id = reader.tgReadObject();
        return new this({userId:_user_id})
    }
}


class EditUserInfoRequest extends TLRequest {
    static CONSTRUCTOR_ID = 0x66b91b70;
    static SUBCLASS_OF_ID = 0x5c53d7d8;

    /**
    :returns help.UserInfo: Instance of either UserInfoEmpty, UserInfo
    */
    constructor(args) {
        super();
        args = args || {}
        this.CONSTRUCTOR_ID = 0x66b91b70;
        this.SUBCLASS_OF_ID = 0x5c53d7d8;

        this.userId = args.userId;
        this.message = args.message;
        this.entities = args.entities;
    }
    async resolve(client, utils) {
        this.user_id = utils.getInputUser(await client.getInputEntity(this.userId))
    }
    getBytes() {
        return Buffer.concat([
            Buffer.from("701bb966","hex"),
            this.userId.getBytes(),
            TLObject.serializeBytes(this.message),
            Buffer.from('15c4b51c', 'hex'),struct.pack('<i', this.entities.length),Buffer.concat(this.entities.map(x => x.getBytes())),
            ])
        }
    static fromReader(reader) {
        let _user_id;
        let _message;
        let _entities;
        let _x;
        let len;
        _user_id = reader.tgReadObject();
        _message = reader.tgReadString();
        reader.readInt();
        _entities = [];
        len = reader.readInt();
        for (let i=0;i<len;i++){
            _x = reader.tgReadObject();
            _entities.push(_x);
            }
            return new this({userId:_user_id,
	message:_message,
	entities:_entities})
        }
    }

module.exports = {
    GetConfigRequest,
    GetNearestDcRequest,
    GetAppUpdateRequest,
    GetInviteTextRequest,
    GetSupportRequest,
    GetAppChangelogRequest,
    SetBotUpdatesStatusRequest,
    GetCdnConfigRequest,
    GetRecentMeUrlsRequest,
    GetProxyDataRequest,
    GetTermsOfServiceUpdateRequest,
    AcceptTermsOfServiceRequest,
    GetDeepLinkInfoRequest,
    GetAppConfigRequest,
    SaveAppLogRequest,
    GetPassportConfigRequest,
    GetSupportNameRequest,
    GetUserInfoRequest,
    EditUserInfoRequest,
};
