<<<<<<< HEAD
/*! File generated by TLObjects' generator. All changes will be ERASED !*/
=======
const api = require('./api')
const LAYER = 105
const tlobjects = {}

>>>>>>> 3f7f5bfa... GramJS: Comment out unused things

const { constructors, requests, patched } = require('./index');
const LAYER = 105;
const tlobjects = {}
for (const tl of [...Object.values(constructors), ...Object.values(requests)]) {
    if (tl.CONSTRUCTOR_ID) {
        tlobjects[tl.CONSTRUCTOR_ID] = tl
    } else {
        for (const sub of Object.values(tl)) {
            tlobjects[sub.CONSTRUCTOR_ID] = sub
        }
    }
}

module.exports = {
    LAYER,
    tlobjects
};
